aliyun-oss:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    bucket-url: yourBucketUrl
    base-path: yourBasePath
byte-tos:
    endpoint: tos-cn-hongkong.bytepluses.com
    region: cn-hongkong
    access-key-id: AKAPOGMzNTNkYWYwNDZiNDk4OGFlMWU0Y2NmYjEzNmUzODE
    access-key-secret: TlRjeFpETmxNemRpT1RsbE5HUTVORGxtTkdNME4yUXhObU5sWkdZNFlUVQ==
    bucket-name: deedmx-file
    bucket-url: https://deedmx-file.tos-cn-hongkong.bytepluses.com
    base-path: file
autocode:
    web: web/src
    root: /Users/halay/code/gin-vue-admin
    root_bak: D:\go_work\src\Ai\rwa\deekmx\gin-vue-admin
    server: server
    module: github.com/flipped-aurora/gin-vue-admin/server
    ai-path: "https://ai.gin-vue-admin.com/{FUNC}/DeedMX/c206c1ee-d2f3-41a9-8b02-2bb69f429953"
aws-s3:
    bucket: xxxxx-10005608
    region: ap-shanghai
    endpoint: ""
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: github.com/flipped-aurora/gin-vue-admin/server
    s3-force-path-style: false
    disable-ssl: false
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
cloudflare-r2:
    bucket: xxxx0bucket
    base-url: https://gin.vue.admin.com
    path: uploads
    account-id: xxx_account_id
    access-key-id: xxx_key_id
    secret-access-key: xxx_secret_key
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - type: ""
      alias-name: ""
      prefix: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      path: ""
      engine: ""
      log-mode: ""
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
disk-list:
    - mount-point: /
email:
    to: 532252324@qq.com
    from: deedmxtech@gmail.com
    host: smtp.gmail.com
    secret: zozwoiadjnwracvx
    nickname: DeedMX
    port: 465
    is-ssl: true
    is-loginauth: false
excel:
    dir: ./resource/excel/
hua-wei-obs:
    path: you-path
    bucket: you-bucket
    endpoint: you-endpoint
    access-key: you-access-key
    secret-key: you-secret-key
jwt:
    signing-key: 8a064c05-5c8f-44bf-a87b-9d667682595c
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store-path: uploads/file
mcp:
    name: GVA_MCP
    version: v1.0.0
    sse_path: /sse
    message_path: /message
    url_prefix: ""
    addr: 8889
    separate: false
minio:
    endpoint: yourEndpoint
    access-key-id: yourAccessKeyId
    access-key-secret: yourAccessKeySecret
    bucket-name: yourBucketName
    use-ssl: false
    base-path: ""
    bucket-url: http://host:9000/yourBucketName
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 100
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts:
        - host: ""
          port: ""
mssql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: deedmx
    username: rwaai
    password: AiRwa1009.
    path: 110.41.59.11
    engine: ""
    log-mode: error
    max-idle-conns: 10000
    max-open-conns: 100000
    singular: false
    log-zap: false
oracle:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
qiniu:
    zone: ZoneHuaDong
    bucket: ""
    img-path: ""
    access-key: ""
    secret-key: ""
    use-https: false
    use-cdn-domains: false
redis:
    name: ""
    addr: 110.41.59.11:6379
    password: AiRwaRds1009.
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
redis-list:
    - name: cache
      addr: 110.41.59.11:6379
      password: AiRwaRds1009.
      db: 0
      useCluster: false
      clusterAddrs:
          - 172.21.0.3:7000
          - 172.21.0.4:7001
          - 172.21.0.2:7002
sqlite:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
system:
    db-type: mysql
    oss-type: byte-tos
    router-prefix: ""
    addr: 8888
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: true
    use-mongo: false
    use-strict-auth: false
    disable-auto-migrate: false
tencent-cos:
    bucket: xxxxx-10005608
    region: ap-shanghai
    secret-id: your-secret-id
    secret-key: your-secret-key
    base-url: https://gin.vue.admin
    path-prefix: github.com/flipped-aurora/gin-vue-admin/server
zap:
    level: info
    prefix: '[deedmx/go-server]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    show-line: true
    log-in-console: true
    retention-day: -1
app-user:
    authority-id: 123
    y-api-url: https://minax-api.devlab.vip
    y-api-time-out: 10
    x-cg-pro-api-key: 'CG-qEPsFVv25eLHRtkKNAiwELyT'
    x-cg-pro-api-url: https://pro-api.coingecko.com/api/v3
    x-cg-api-ids: #bitcoin,ethereum,ripple,binancecoin,solana,tron,staked-ether,dogecoin
        - bitcoin
        - ethereum
        - ripple
        - binancecoin
        - solana
        - tron
        - staked-ether
        - dogecoin
    href-url: "http://110.41.59.11/api/"
    bltcy-api-url: "https://api.bltcy.ai"
    bltcy-api-url2: "https://hk-api.gptbest.vip"
    bltcy-api-key: "sk-jYML4I6KAMGNbrRnp5sXuXu1FYTkrLKCO0WSwU0eoCzT8yQC"